//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace SimpleMessage.GrainInterfaces
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using Orleans;
    using Orleans.Runtime;
    using System.Collections;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class SmsObserverFactory
    {
        

            public static SimpleMessage.GrainInterfaces.ISmsObserver Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return SmsObserverReference.Cast(grainRef);
            }

        private static global::Orleans.CodeGeneration.IGrainMethodInvoker methodInvoker;

        public async static System.Threading.Tasks.Task<SimpleMessage.GrainInterfaces.ISmsObserver> CreateObjectReference(SimpleMessage.GrainInterfaces.ISmsObserver obj)
        {
            if (methodInvoker == null) methodInvoker = new SmsObserverMethodInvoker();
            return SmsObserverFactory.Cast(await global::Orleans.Runtime.GrainReference.CreateObjectReference(obj, methodInvoker));
        }

        public static System.Threading.Tasks.Task DeleteObjectReference(SimpleMessage.GrainInterfaces.ISmsObserver reference)
        {
            return global::Orleans.Runtime.GrainReference.DeleteObjectReference(reference);
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("SimpleMessage.GrainInterfaces.SimpleMessage.GrainInterfaces.ISmsObserver")]
        internal class SmsObserverReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, SimpleMessage.GrainInterfaces.ISmsObserver
        {
            

            public static SimpleMessage.GrainInterfaces.ISmsObserver Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (SimpleMessage.GrainInterfaces.ISmsObserver) global::Orleans.Runtime.GrainReference.CastInternal(typeof(SimpleMessage.GrainInterfaces.ISmsObserver), (global::Orleans.Runtime.GrainReference gr) => { return new SmsObserverReference(gr);}, grainRef, 543789594);
            }
            
            protected internal SmsObserverReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal SmsObserverReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 543789594;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "SimpleMessage.GrainInterfaces.SimpleMessage.GrainInterfaces.ISmsObserver";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                SmsObserverReference input = ((SmsObserverReference)(original));
                return ((SmsObserverReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                SmsObserverReference input = ((SmsObserverReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return SmsObserverReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return SmsObserverMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            void SimpleMessage.GrainInterfaces.ISmsObserver.NewMessage(string message)
            {

                base.InvokeOneWayMethod(-1395251043, new object[] {message} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("SimpleMessage.GrainInterfaces.SimpleMessage.GrainInterfaces.ISmsObserver", 543789594)]
    internal class SmsObserverMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 543789594;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 543789594:  // ISmsObserver
                        switch (methodId)
                        {
                            case -1395251043: 
                                ((ISmsObserver)grain).NewMessage((System.String)arguments[0]); return System.Threading.Tasks.Task.FromResult((object)true);
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 543789594:  // ISmsObserver
                    switch (methodId)
                    {
                        case -1395251043:
                            return "NewMessage";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class SmsGrainFactory
    {
        

                        public static SimpleMessage.GrainInterfaces.ISmsGrain GetGrain(System.String primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(SimpleMessage.GrainInterfaces.ISmsGrain), -988094874, primaryKey));
                        }

                        public static SimpleMessage.GrainInterfaces.ISmsGrain GetGrain(System.String primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(SimpleMessage.GrainInterfaces.ISmsGrain), -988094874, primaryKey, grainClassNamePrefix));
                        }

            public static SimpleMessage.GrainInterfaces.ISmsGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return SmsGrainReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("SimpleMessage.GrainInterfaces.SimpleMessage.GrainInterfaces.ISmsGrain")]
        internal class SmsGrainReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, SimpleMessage.GrainInterfaces.ISmsGrain
        {
            

            public static SimpleMessage.GrainInterfaces.ISmsGrain Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (SimpleMessage.GrainInterfaces.ISmsGrain) global::Orleans.Runtime.GrainReference.CastInternal(typeof(SimpleMessage.GrainInterfaces.ISmsGrain), (global::Orleans.Runtime.GrainReference gr) => { return new SmsGrainReference(gr);}, grainRef, -988094874);
            }
            
            protected internal SmsGrainReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal SmsGrainReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return -988094874;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "SimpleMessage.GrainInterfaces.SimpleMessage.GrainInterfaces.ISmsGrain";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                SmsGrainReference input = ((SmsGrainReference)(original));
                return ((SmsGrainReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                SmsGrainReference input = ((SmsGrainReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return SmsGrainReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return ((interfaceId == this.InterfaceId) 
                            || (interfaceId == -1277021679));
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return SmsGrainMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task SimpleMessage.GrainInterfaces.ISmsGrain.NewMessage(string message)
            {

                return base.InvokeMethodAsync<object>(-1395251043, new object[] {message} );
            }
            
            System.Threading.Tasks.Task<System.Collections.Generic.List<string>> SimpleMessage.GrainInterfaces.ISmsGrain.GetMessages()
            {

                return base.InvokeMethodAsync<System.Collections.Generic.List<System.String>>(1887469791, new object[] {} );
            }
            
            System.Threading.Tasks.Task SimpleMessage.GrainInterfaces.ISmsGrain.WatchForMessages(SimpleMessage.GrainInterfaces.ISmsObserver observer)
            {
global::Orleans.CodeGeneration.GrainFactoryBase.CheckGrainObserverParamInternal(observer);

                return base.InvokeMethodAsync<object>(-703051256, new object[] {observer is global::Orleans.Grain ? SimpleMessage.GrainInterfaces.SmsObserverFactory.Cast(observer.AsReference()) : observer} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("SimpleMessage.GrainInterfaces.SimpleMessage.GrainInterfaces.ISmsGrain", -988094874)]
    internal class SmsGrainMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return -988094874;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case -988094874:  // ISmsGrain
                        switch (methodId)
                        {
                            case -1395251043: 
                                return ((ISmsGrain)grain).NewMessage((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 1887469791: 
                                return ((ISmsGrain)grain).GetMessages().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -703051256: 
                                return ((ISmsGrain)grain).WatchForMessages((ISmsObserver)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }case -1277021679:  // IGrainWithStringKey
                        switch (methodId)
                        {
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case -988094874:  // ISmsGrain
                    switch (methodId)
                    {
                        case -1395251043:
                            return "NewMessage";
                    case 1887469791:
                            return "GetMessages";
                    case -703051256:
                            return "WatchForMessages";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }
                case -1277021679:  // IGrainWithStringKey
                    switch (methodId)
                    {
                        
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
